"""Константные значения для работы приложений."""

MAX_LENGTH_NAME = 150
TAG_LENGTH = 32
INGREDIENT_LENGTH = 128
MEASUREMENT_LENGTH = 64
RECIPE_LENGTH = 256
MIN_VALIDATOR_VALUE = 1
MAX_VALIDATOR_VALUE = 32000
SHORT_LINK_LENGTH = 20
ADMIN_LIST_PER_PAGE = 10
